name: Deploy functions CD

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      run_apim_script_update:
        type: boolean
        default: false
      runner_group:
        type: string
        required: true
      function_name:
        type: string
        required: true
      csprojpath:
        type: string
        required: true
### env vars
# 1. csprojpath
# 2. function_name - inputs
# 3. RESOURCEGROUP

jobs:
  deploy:
    runs-on: 
      group: ${{ inputs.runner_group }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.environment }}
          path: build

      - name: locate artifact
        run: |
          ls
          echo "build files"
          cd build
          ls

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - id: approval
        uses: ekeel/approval-action@v1.0.3
        if: github.event.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          # A GitHub token with repo scope.
          # The default secrets.GITHUB_TOKEN does not work with octokit to open/update/close issues.
          token: ${{ secrets.PAT_TOKEN_GH }}
          # A comma separated list of GitHub usernames that are allowed to approve.
          # Example: 'ekeel,octocat'
          approvers: 'XE064259743_EYGS,US016020768_EYGS,US015802021_EYGS,20230108971_EYGS'
          # The number of approvals/rejections required to continue the workflow.
          minimumApprovals: '1'
          # The title of the issue to create.
          issueTitle: 'Deploy function: ${{ inputs.function_name }} in RG: ${{ vars.resourceGroup }}'
          # The body of the issue to create.
          issueBody: 'Deploy function: ${{ inputs.function_name }} in RG: ${{ vars.resourceGroup }}'
          # A comma separated list of labels to add to the issue.
          issueLabels: 'ManualApproval,ApprovalAction'
          # Exclude the workflow initiator from the list of approvers.
          excludeInitiator: 'false'
          # A comma separated list of words that will be used to approve.
          approveWords: 'approve, approved'
          # A comma separated list of words that will be used to reject.
          rejectWords: 'deny, denied, reject, rejected'
          # The number of minutes to wait between checks for approvals.
          waitInterval: '1'
          # The number of minutes to wait before timing out.
          waitTimeout: '60'

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.function_name }}
          package: 'build'
