name: Build and Deploy Kernel

on:
  create:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select the environment'
        options:
        - dev
        - dev1
        - dev2
        - dev3
        - qa
        - uat-lab
        - uat-pilot
        - uat-prod
        - prod-lab
        - prod-pilot
        - prod
      checkmarx:
        type: boolean
        required: false
        default: false
      mend:
        type: boolean
        required: false
        default: false
  push:
    paths:
      - services/kernelmemory/**
    branches:
      - main
      - release/*
      - develop
      - feature/*
      - release_QA/*
      - dev_1
      - dev_2
      - dev_3
      - dev_1/**
      - dev_2/**
      - dev_3/**
      - integrate-*
      - release_UAT/*
      
permissions:
      id-token: write
      contents: read

# env:
#   # build
#   csproj_name: 'Service'
#   csprojpath: 'services/kernelmemory/service'
#   checkmarx_proj_name: KernelMemory
#   mend_proj_name: KernelMemory
#   # deploy
#   apiid: ''
#   apipath: ''
#   apimproductname: ''
#   csprojpath: 'services/kernelmemory/service'

jobs:
  build-kernel-eyx-dev:
    name: build-kernel-eyx-dev
    if: github.event.ref == 'refs/heads/develop' || startsWith(github.event.ref, 'refs/heads/integrate-')
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: dev
      environment_service: Development
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-dev:
    name: deploy-kernel-eyx-dev
    needs: build-kernel-eyx-dev
    if: github.event.ref == 'refs/heads/develop' || startsWith(github.event.ref, 'refs/heads/integrate-')
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: dev
      runner_group: large-runner-vnet-eyx
      webapp_name: USEDCXS05HWAP04
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-dev1:
    name: build-kernel-eyx-dev1
    if: startsWith(github.event.ref, 'refs/heads/dev_1') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev1' && (startsWith(github.event.ref, 'refs/heads/dev_1') || startsWith(github.event.ref, 'refs/heads/feature/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: dev1
      environment_service: Development1
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-dev1:
    name: deploy-kernel-eyx-dev1
    needs: build-kernel-eyx-dev1
    if: startsWith(github.event.ref, 'refs/heads/dev_1') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev1' && (startsWith(github.event.ref, 'refs/heads/dev_1') || startsWith(github.event.ref, 'refs/heads/feature/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: dev1
      runner_group: large-runner-vnet-eyx
      webapp_name: USEDCXS05HWAP08
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-dev2:
    name: build-kernel-eyx-dev2
    if: startsWith(github.event.ref, 'refs/heads/dev_2') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev2' && (startsWith(github.event.ref, 'refs/heads/dev_2') || startsWith(github.event.ref, 'refs/heads/feature/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: dev2
      environment_service: Development2
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-dev2:
    name: deploy-kernel-eyx-dev2
    needs: build-kernel-eyx-dev2
    if: startsWith(github.event.ref, 'refs/heads/dev_2') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev2' && (startsWith(github.event.ref, 'refs/heads/dev_2') || startsWith(github.event.ref, 'refs/heads/feature/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: dev2
      runner_group: large-runner-vnet-eyx
      webapp_name: USEDCXS05HWAP0C
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-dev3:
    name: build-kernel-eyx-dev3
    if: startsWith(github.event.ref, 'refs/heads/dev_3') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev3' && (startsWith(github.event.ref, 'refs/heads/dev_3') || startsWith(github.event.ref, 'refs/heads/feature/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: dev3
      environment_service: Development3
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-dev3:
    name: deploy-kernel-eyx-dev3
    needs: build-kernel-eyx-dev3
    if: startsWith(github.event.ref, 'refs/heads/dev_3') || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev3' && (startsWith(github.event.ref, 'refs/heads/dev_3') || startsWith(github.event.ref, 'refs/heads/feature/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: dev3
      runner_group: large-runner-vnet-eyx
      webapp_name: USEDCXS05HWAP0G
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-qa:
    name: build-kernel-eyx-qa
    if: (startsWith(github.event.ref,'refs/heads/release_QA/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_QA/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'qa' && startsWith(github.event.ref,'refs/heads/release_QA/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      runner_group: large-runner-vnet-eyx-qa
      environment: qa
      environment_service: qa
      dotnet_tools: false
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-qa:
    name: deploy-kernel-eyx-qa
    needs: build-kernel-eyx-qa
    if: (startsWith(github.event.ref,'refs/heads/release_QA/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_QA/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'qa' && startsWith(github.event.ref,'refs/heads/release_QA/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: qa
      runner_group: large-runner-vnet-eyx-qa
      webapp_name: useqcxs05hwap04
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-uat-lab:
    name: build-kernel-eyx-uat-lab
    if: (startsWith(github.event.ref,'refs/heads/release_UAT/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_UAT/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'uat-lab' && startsWith(github.event.ref,'refs/heads/release_UAT/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      runner_group: large-runner-grp-eyx-uat
      environment: uat-lab
      environment_service: uat-lab
      dotnet_tools: false
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-uat-lab:
    name: deploy-kernel-eyx-uat-lab
    needs: build-kernel-eyx-uat-lab
    if: (startsWith(github.event.ref,'refs/heads/release_UAT/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_UAT/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'uat-lab' && startsWith(github.event.ref,'refs/heads/release_UAT/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: uat-lab
      runner_group: large-runner-grp-eyx-uat
      webapp_name: USEUEYXU01WAP04
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-uat-pilot:
    name: build-kernel-eyx-uat-pilot
    if: (startsWith(github.event.ref,'refs/heads/release_UAT/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_UAT/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'uat-pilot' && startsWith(github.event.ref,'refs/heads/release_UAT/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: uat-pilot
      environment_service: uat-pilot
      dotnet_tools: false
      runner_group: large-runner-grp-eyx-uat
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-uat-pilot:
    name: deploy-kernel-eyx-uat-pilot
    needs: build-kernel-eyx-uat-pilot
    if: (startsWith(github.event.ref,'refs/heads/release_UAT/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_UAT/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'uat-pilot' && startsWith(github.event.ref,'refs/heads/release_UAT/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: uat-pilot
      runner_group: large-runner-grp-eyx-uat
      webapp_name: USEUEYXU01WAP08
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-uat-prod:
    name: build-kernel-eyx-uat-prod
    if: (startsWith(github.event.ref,'refs/heads/release_UAT/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_UAT/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'uat-prod' && startsWith(github.event.ref,'refs/heads/release_UAT/')))
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: uat-prod
      environment_service: uat-prod
      dotnet_tools: false
      runner_group: large-runner-grp-eyx-uat
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-uat-prod:
    name: deploy-kernel-eyx-uat-prod
    needs: build-kernel-eyx-uat-prod
    if: (startsWith(github.event.ref,'refs/heads/release_UAT/') || github.event_name == 'create' && github.event.ref_type == 'branch' && (startsWith(github.ref, 'refs/heads/release_UAT/')) || (github.event_name == 'workflow_dispatch' && inputs.environment == 'uat-prod' && startsWith(github.event.ref,'refs/heads/release_UAT/')))
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: uat-prod
      runner_group: large-runner-grp-eyx-uat
      webapp_name: USEUEYXU01WAP0C
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-prod-lab:
    name: build-kernel-eyx-prod-lab
    if: github.event.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: prod-lab
      environment_service: prod-lab
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx-prod
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-prod-lab:
    name: deploy-kernel-eyx-prod-lab
    needs: build-kernel-eyx-prod-lab
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: prod-lab
      runner_group: large-runner-vnet-eyx-prod
      webapp_name: 'USEPEYXP01WAP08'
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit


  build-kernel-eyx-prod-pilot:
    name: build-kernel-eyx-prod-pilot
    if: github.event.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: prod-pilot
      environment_service: prod-pilot
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx-prod
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-prod-pilot:
    name: deploy-kernel-eyx-prod-pilot
    needs: build-kernel-eyx-prod-pilot
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: prod-pilot
      runner_group: large-runner-vnet-eyx-prod
      webapp_name: 'USEPEYXP01WAP0C'
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit

  build-kernel-eyx-prod:
    name: build-kernel-eyx-prod
    if: github.event.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/ci-dotnet.yaml
    with:
      environment: prod
      environment_service: prod
      dotnet_tools: false
      runner_group: large-runner-vnet-eyx-prod
      csproj_name: 'Service'
      csprojpath: 'services/kernelmemory/service'
      checkmarx_proj_name: KernelMemory
      mend_proj_name: KernelMemory
    secrets: inherit
  deploy-kernel-eyx-prod:
    name: deploy-kernel-eyx-prod
    needs: build-kernel-eyx-prod
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/cd-webapp.yml
    with:
      environment: prod
      runner_group: large-runner-vnet-eyx-prod
      webapp_name: 'USEPEYXP01WAP0G'
      csprojpath: 'services/kernelmemory/service'
    secrets: inherit
