name: Build WebUI EYX

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      runner_group:
        type: string
        required: true
      checkmarx:
        type: boolean
        required: false
        default: false
      mend:
        type: boolean
        required: false
        default: false

  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      checkmarx:
        type: boolean
        required: false
        default: false
      mend:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: 
      group: ${{ inputs.runner_group }}
    environment: ${{ inputs.environment }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Checkmarx CxFlow Scan - SAST
      ## Because of a GitHub Action limitation, the condition needs to check the literal value of the input or the variable.
      - name: Checkmarx CxFlow Action and continue on error
        if: ${{ vars.CHECKMARX == 'true' || inputs.checkmarx == 'true' }}
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
        with:
          project: 'EYQ-EYX-${{ vars.checkmarx_proj_name }}-${{ inputs.environment }}'
          team: 'CxServer/SP/EY/Service Lines/CT'
          checkmarx_url: 'https://vmey.checkmarx.net/'
          checkmarx_username: ${{ vars.CHECKMARX_EYX_USER }}
          checkmarx_password: ${{ secrets.CHECKMARX_EYX_PASS }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          scanners: sast
          bug_tracker: Sarif
          preset: EY-Recommended
          break_build: ${{ vars.CHECKMARX_BREAK_BUILD }}
          params: --cx-flow.thresholds.high ${{ vars.checkmarx_threshold_high }} --cx-flow.thresholds.medium ${{ vars.checkmarx_threshold_medium }}


      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.15.0"

      # Step 3: Install all dependencies required for the build
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Build the app
      - name: Build WebUI
        run: |
          npm run build -- --env=${{ inputs.environment }}


      # - name: Qualys WAS scan action step
      #   uses: Qualys/github_action_qwas@main
      #   id: was
      #   with:
      #     API_SERVER: ${{ vars.API_SERVER }}
      #     QUALYS_USERNAME: 1110732
      #     QUALYS_PASSWORD: 
      #     WEBAPP_ID: 1132795901-GTP-FS/RAPToR
      #     SCAN_NAME: 
      #     SCAN_TYPE: VULNERABILITY
      #     AUTH_RECORD: Other
      #     WAIT_FOR_RESULT: 60*24
      #     INTERVAL: 5

      # Step 5: Run Mend scan. This requires the app to have been built first.
        ## Because of a GitHub Action limitation, the condition needs to check the literal value of the input or the variable.
      - name: "Mend (formerly whitesource) Scan and continue on error "
        if: ${{ vars.MEND == 'true' || inputs.mend == 'true' }}
        uses: ey-org/oss-scanner@master
        with:
          apm-id: APM0023852
          spr-id: 'SPR-17504'
          portfolio: 'CT'
          projectName: 'EYQ-EYX-${{ vars.mend_proj_name }}-${{ inputs.environment }}'
          mend-key: ${{ secrets.MEND_ACTION_STS }}
          validationKey: ${{  secrets.ARCHER_SPR_API_TOKEN }}
          connectionKey: ${{ secrets.INFOSEC_CONNECTIONKEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ inputs.environment }}
          path: dist/
