name: Deploy WebUI EYX

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      runner_group:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    runs-on: 
      group: ${{ inputs.runner_group }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ inputs.environment }}
          path: dist

      # - name: 'Login to Azure'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show WebApp
        run: |
          az webapp show --name ${{ vars.APP_SERVICE }} --resource-group ${{ vars.RESOURCE_GROUP }} --query state -o tsv

      - name: locate artifact
        run: |
          ls
          echo "dist files"
          cd dist
          ls

      - id: approval
        uses: ekeel/approval-action@v1.0.3
        if: github.event.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          # A GitHub token with repo scope.
          # The default secrets.GITHUB_TOKEN does not work with octokit to open/update/close issues.
          token: ${{ secrets.PAT_TOKEN_GH }}
          # A comma separated list of GitHub usernames that are allowed to approve.
          # Example: 'ekeel,octocat'
          approvers: 'XE064259743_EYGS,US016020768_EYGS,US015802021_EYGS,20230108971_EYGS'
          # The number of approvals/rejections required to continue the workflow.
          minimumApprovals: '1'
          # The title of the issue to create.
          issueTitle: 'Deploy webapp: ${{ vars.APP_SERVICE }} in RG: ${{ vars.RESOURCE_GROUP }}'
          # The body of the issue to create.
          issueBody: 'Deploy webapp: ${{ inputs.APP_SERVICE }} in RG: ${{ vars.RESOURCE_GROUP }}'
          # A comma separated list of labels to add to the issue.
          issueLabels: 'ManualApproval,ApprovalAction'
          # Exclude the workflow initiator from the list of approvers.
          excludeInitiator: 'false'
          # A comma separated list of words that will be used to approve.
          approveWords: 'approve, approved'
          # A comma separated list of words that will be used to reject.
          rejectWords: 'deny, denied, reject, rejected'
          # The number of minutes to wait between checks for approvals.
          waitInterval: '1'
          # The number of minutes to wait before timing out.
          waitTimeout: '60'

      - name: Deploy to Azure webapps
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ vars.APP_SERVICE }}'
          package: 'dist'
          app-settings-json: |
            {
              "WEBSITE_NODE_DEFAULT_VERSION": "16.15.0"
            }
