name: Deploy WebUI EYX

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      runner_group:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    runs-on: 
      group: ${{ inputs.runner_group }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ inputs.environment }}
          path: dist

      # - name: 'Login to Azure'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show WebApp
        run: |
          az webapp show --name ${{ vars.APP_SERVICE }} --resource-group ${{ vars.RESOURCE_GROUP }} --query state -o tsv

      - name: locate artifact
        run: |
          ls
          echo "dist files"
          cd dist
          ls

      - name: Deploy to Azure webapps
        uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ vars.APP_SERVICE }}'
          package: 'dist'
          app-settings-json: |
            {
              "WEBSITE_NODE_DEFAULT_VERSION": "16.15.0"
            }
