locals {
  # TAGS
  ## Base tags per main environment
  environment_base_tags = {
    QA = {
      DEPLOYMENT_ID = "CXS05H"
      ENGAGEMENT_ID = "I-68403024"
      OWNER         = "dante.ciai@gds.ey.com, juan.mercade@gds.ey.com, gustavo.sosa@gds.ey.com"
      ENVIRONMENT   = "QA"
    }
    UAT = {
      DEPLOYMENT_ID = "EYXU01"
      ENGAGEMENT_ID = "I-69197406"
      OWNER         = "dante.ciai@gds.ey.com, juan.mercade@gds.ey.com, gustavo.sosa@gds.ey.com"
      ENVIRONMENT   = "UAT"
    }
    PROD = {
      DEPLOYMENT_ID = "EYXP01"
      ENGAGEMENT_ID = "I-69197406"
      OWNER         = "dante.ciai@gds.ey.com, juan.mercade@gds.ey.com, gustavo.sosa@gds.ey.com"
      ENVIRONMENT   = "PROD"
    }
  }

  general_tags = local.environment_base_tags[var.env]

  # Base private DNS zones - common across all environments
  base_private_dns_zones = {
    redis                 = "privatelink.redis.cache.windows.net"
    servicebus            = "privatelink.servicebus.windows.net"
    cosmosdb              = "privatelink.documents.azure.com"
    cosmosdb_postgresql   = "privatelink.postgres.cosmos.azure.com"
    storage_blob          = "privatelink.blob.core.windows.net"
    storage_queue         = "privatelink.queue.core.windows.net"
    storage_table         = "privatelink.table.core.windows.net"
    app_service           = "privatelink.azurewebsites.net"
    signalr               = "privatelink.service.signalr.net"
    openai                = "privatelink.openai.azure.com"
    document_intelligence = "privatelink.cognitiveservices.azure.com"
    container_registry    = "privatelink.azurecr.io"
  }

  # Additional zones for UAT/PROD only
  uat_prod_additional_zones = {
    speech                    = "privatelink.speech.azure.com"
    container_app             = "privatelink.azurecontainerapps.io"
    container_app_environment = "privatelink.${lower(data.azurerm_resource_group.admin.location)}.azurecontainerapps.io"
  }

  # QA additional zones (only has container_app zone, not container_app_environment or speech)
  # Note: QA uses a region-specific container app zone derived from the admin resource group location
  qa_additional_zones = {
    container_app = "privatelink.${lower(data.azurerm_resource_group.admin.location)}.azurecontainerapps.io"
  }

  # Merge zones based on environment
  private_dns_zones = var.env == "QA" ? merge(
    local.base_private_dns_zones,
    local.qa_additional_zones
    ) : merge(
    local.base_private_dns_zones,
    local.uat_prod_additional_zones
  )

  private_dns_zone_tags = {
    redis                     = { "hidden-title" = "EYX - ${var.env} - Redis Private DNS Zone" }
    servicebus                = { "hidden-title" = "EYX - ${var.env} - Service Bus Private DNS Zone" }
    cosmosdb                  = { "hidden-title" = "EYX - ${var.env} - CosmosDB Private DNS Zone" }
    cosmosdb_postgresql       = { "hidden-title" = "EYX - ${var.env} - PostgreSQL Private DNS Zone" }
    storage_blob              = { "hidden-title" = "EYX - ${var.env} - Storage Blob Private DNS Zone" }
    storage_queue             = { "hidden-title" = "EYX - ${var.env} - Storage Queue Private DNS Zone" }
    storage_table             = { "hidden-title" = "EYX - ${var.env} - Storage Table Private DNS Zone" }
    app_service               = { "hidden-title" = "EYX - ${var.env} - App Service Private DNS Zone" }
    signalr                   = { "hidden-title" = "EYX - ${var.env} - SignalR Private DNS Zone" }
    speech                    = { "hidden-title" = "EYX - ${var.env} - Speech Private DNS Zone" }
    openai                    = { "hidden-title" = "EYX - ${var.env} - OpenAI Private DNS Zone" }
    document_intelligence     = { "hidden-title" = "EYX - ${var.env} - Document Intelligence Private DNS Zone" }
    container_app             = { "hidden-title" = "EYX - ${var.env} - Container App Private DNS Zone" }
    container_registry        = { "hidden-title" = "EYX - ${var.env} - Container Registry Private DNS Zone" }
    container_app_environment = { "hidden-title" = "EYX - ${var.env} - Container App Environment Private DNS Zone" }
  }

  # Dynamic merging - automatically merges general_tags with each resource-specific tag set
  merged_tags = {
    for key, dns_zone_tags in local.private_dns_zone_tags :
    key => merge(local.general_tags, dns_zone_tags)
  }

  # Virtual Network Links Configuration per Zone and Environment
  # This centralizes all environment-specific VNet link logic for cleaner code
  virtual_network_links_per_zone = {
    for zone_key, zone_name in local.private_dns_zones :
    zone_key => var.env == "QA" ? (
      # QA Environment - Simple structure with special cases per zone
      zone_key == "app_service" ? {
        # app_service has different autogenerated link names in QA
        # IMPORTANT: These names must match existing Azure resources to avoid recreation
        admin = {
          name   = "adminvnet"
          vnetid = data.azurerm_virtual_network.admin_vnet.id
        }
        frontend = {
          name   = "3r4xxrz4oyvua" # Autogenerated by Azure Portal - DO NOT CHANGE
          vnetid = data.azurerm_virtual_network.lab_frontend_vnet.id
        }
        backend = {
          name   = "backendvnet"
          vnetid = data.azurerm_virtual_network.lab_backend_vnet.id
        }
        } : zone_key == "signalr" ? {
        # signalr has NO VNet links in QA - SignalR service not deployed in this environment
        } : zone_key == "container_app" ? {
        # container_app only has admin link in QA
        # IMPORTANT: Link name must match existing Azure resource to avoid recreation
        admin = {
          name   = "useqcxs05hcae01-link" # Generated by Container App Environment deployment - DO NOT CHANGE
          vnetid = data.azurerm_virtual_network.admin_vnet.id
        }
        } : {
        # Default QA configuration for most zones (3 VNets)
        # IMPORTANT: Backend link name must match existing Azure resource to avoid recreation
        admin = {
          name   = "adminvnet"
          vnetid = data.azurerm_virtual_network.admin_vnet.id
        }
        frontend = {
          name   = "frontendvnet"
          vnetid = data.azurerm_virtual_network.lab_frontend_vnet.id
        }
        backend = {
          name   = "gxu3fkrqiwees" # Autogenerated by Azure Portal - DO NOT CHANGE
          vnetid = data.azurerm_virtual_network.lab_backend_vnet.id
        }
      }
      ) : {
      # UAT/PROD Environment - Complex structure (admin + 6 app VNets for lab/pilot/prod)
      admin = {
        name   = "${var.env}-admin-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.admin_vnet.id
      }

      # LAB Environment Links
      frontend-lab = {
        name   = "${var.env}-lab-frontend-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.lab_frontend_vnet.id
      }
      backend-lab = {
        name   = "${var.env}-lab-backend-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.lab_backend_vnet.id
      }

      # PILOT Environment Links
      frontend-pilot = {
        name   = "${var.env}-pilot-frontend-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.pilot_frontend_vnet[0].id
      }
      backend-pilot = {
        name   = "${var.env}-pilot-backend-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.pilot_backend_vnet[0].id
      }

      # PROD Environment Links
      frontend-prod = {
        name   = "${var.env}-prod-frontend-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.prod_frontend_vnet[0].id
      }
      backend-prod = {
        name   = "${var.env}-prod-backend-vnet-${zone_key}-link"
        vnetid = data.azurerm_virtual_network.prod_backend_vnet[0].id
      }
    }
  }

  # Management Lock Configuration
  # Centralized lock policy - all environments get CanNotDelete locks on DNS zones
  dns_zone_lock = {
    kind  = "CanNotDelete"
    notes = "Prevents accidental deletion of ${var.env} Private DNS Zone - Managed by Terraform"
  }
}